name: Library
api-version: 1.13
version: 1.1.0
description: A simple plugin, which allows you to easily add books into your minecraft server.
author: Bjorn Beishline
main: com.library.Library
description: Gives the player a list of books to read upon typing the command "/read".
database: false
commands:
   read:
      usage: /<command>
      description: Read any book available in the library.
   library:
      usage: /<command>
      description: Get a library of books to select from in an interface.
permissions:
   library.read:
      description: Needed to use the /read command
      default: true
   library.read.books:
      description: Needed to use the /read <bookname> command
      default: true
   library.read.books.chapter:
      description: Needed to use the /read <bookname> <chapter> command and get book
      default: true
   library.library:
      description: Needed to use the /library command
      default: true
   library.library.book:
      description: Needed to use the /library <bookname> command
      default: true
